Segfault on openDbi when Env has not been previously opened

I get a Segmentation Fault when I run the following program:
```
var lmdb = require('./index.js')
var env = new lmdb.Env();
var dbi = env.openDbi({name: "myPrettyDatabase", create: true})
```

Here is the GDB backtrace:
```
Thread 1 "node_g" received signal SIGSEGV, Segmentation fault.
0x00007fddcc1cfbe2 in mdb_txn_renew0 (txn=0x0) at ../dependencies/lmdb/libraries/liblmdb/mdb.c:2996
2996            MDB_env *env = txn->mt_env;
(gdb) bt
#0  0x00007fddcc1cfbe2 in mdb_txn_renew0 (txn=0x0) at ../dependencies/lmdb/libraries/liblmdb/mdb.c:2996
#1  0x00007fddcc1d05e4 in mdb_txn_begin (env=0x55e9f940f590, parent=0x0, flags=0, ret=0x7fff680575d0) at ../dependencies/lmdb/libraries/liblmdb/mdb.c:3244
#2  0x00007fddcc1f4b81 in DbiWrap::ctor (info=...) at ../src/dbi.cpp:127
#3  0x00007fddcc1e254d in Nan::imp::FunctionCallbackWrapper (info=...) at ../../nan/nan_callbacks_12_inl.h:177
```

I would expect to get a warning instead.

Could we catch this in the call to openDbi, somewhere around here?
https://github.com/Venemo/node-lmdb/blob/ef1c4242ba75b8f8ce755b52af33e470ca728ab7/src/env.cpp#L594
